// Generated by IcedCoffeeScript 108.0.9
(function() {
  var mp, pp, set_opt, set_opts, _opts;

  pp = require('purepack');

  mp = pp;

  if ((mp == null) && (pp == null)) {
    throw new Error("Need either msgpack or purepack to run");
  }

  _opts = {};

  exports.set_opt = set_opt = function(k, v) {
    return _opts[k] = v;
  };

  exports.set_opts = set_opts = function(o) {
    return _opts = o;
  };

  exports.pack = function(b) {
    return mp.pack(b);
  };

  exports.unpack = function(b) {
    var dat, err;
    err = dat = null;
    try {
      dat = mp.unpack(b);
    } catch (_error) {
      err = _error;
    }
    return [err, dat];
  };

}).call(this);
